name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build and test
    permissions:
      # allow the release step to comment on
      # issues, pull requests, and write to the repo
      contents: write
      issues: write
      pull-requests: write
      # Required for OIDC to let NPM registry know
      # that this workflow is trusted
      id-token: write
    steps:
      - uses: actions/checkout@v7
        # https://github.com/bahmutov/npm-install
      - uses: bahmutov/npm-install@v1
      - name: Check dependencies
        run: npm run deps
      - name: Run tests
        run: npm t
      - name: Release
        if: github.ref == 'refs/heads/master'
        # https://github.com/cycjimmy/semantic-release-action
        uses: cycjimmy/semantic-release-action@v6
        with:
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
