name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build and test
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Check dependencies
        run: npm run deps
      - name: Run tests
        run: npm t
      - name: Release
        if: github.ref == 'refs/heads/master'
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
